<a href="https://colab.research.google.com/github/mostafa-ja/sample/blob/master/PyTorch_Tutorial_09_Dataset_and_DataLoader_Batch_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[link text](https://www.youtube.com/watch?v=PXOzkkB5eH0&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4&index=9)

In [1]:
import torch
import torchvision
from torch.utils.data import Dataset , DataLoader
import numpy as np
import math

In [7]:
data is (178, 14) and first column is y (1 or 2 or 3)
!wget https://raw.githubusercontent.com/python-engineer/pytorchTutorial/master/data/wine/wine.csv

--2022-08-09 19:37:00--  https://raw.githubusercontent.com/python-engineer/pytorchTutorial/master/data/wine/wine.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10889 (11K) [text/plain]
Saving to: ‘wine.csv’

wine.csv            100%[===================>]  10.63K  --.-KB/s    in 0s      

2022-08-09 19:37:00 (42.1 MB/s) - ‘wine.csv’ saved [10889/10889]



In [13]:
xy[:,[0]].shape

(178, 1)

In [15]:
xy[:,0].shape

(178,)

In [17]:
class WineDataset(Dataset):
  
  def __init__(self):
    #loading data
    xy = np.loadtxt('/content/wine.csv',delimiter=',',dtype=np.float32, skiprows=1)
    self.x = torch.from_numpy(xy[:,1:])
    self.y = torch.from_numpy(xy[:,[0]])   # ATTENTION : xy[:,[0]].shape=(178, 1) & xy[:,0].shape=(178,)
    self.n_samples = xy.shape[0]

  def __getitem__(self, index):            # means , instance[index] gives x[index],y[index]
    return self.x[index],self.y[index]     # ex : data = WineDataset() , data[3] = x[3],y[3]

  def __len__(self):               # we define that len(instance) gives n_samples
    return self.n_samples

In [18]:
# test data

dataset = WineDataset()
irst_data = dataset[0]  # dataset[0] = x[0],y[0]
features,labels = first_data
print(features)  # x[0]
print(labels)    # y[0]

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03])
tensor([1.])


In [22]:
len(dataset)

178

Why we defined  __ getitem__(self,index):

for using batch samples , we want to get for exmaple 10 samples of data every call, so when we call dataset[index : index+10], it gives us  x[index : inex+10],y[index:index+10] together which we can separate them

Also we use dataloader to get data litlle by litlle without filling memory

In [24]:
dataset = WineDataset()
dataloader = DataLoader(dataset=dataset, batch_size=4, shuffle=True, num_workers=2) 
# Num_workers tells the data loader instance how many sub-processes to use for data loading. If the num_worker is zero (default)
# the GPU has to weight for CPU to load data. Theoretically, greater the num_workers, more efficiently the CPU load data and less the GPU has to wait


# test dataloader , we are going to get one batch data (4 samples)
dataiter = iter(dataloader)
data = dataiter.next()
features,labels = data
print(features,'\n',labels) # 4 samples

tensor([[1.2670e+01, 9.8000e-01, 2.2400e+00, 1.8000e+01, 9.9000e+01, 2.2000e+00,
         1.9400e+00, 3.0000e-01, 1.4600e+00, 2.6200e+00, 1.2300e+00, 3.1600e+00,
         4.5000e+02],
        [1.2080e+01, 1.3900e+00, 2.5000e+00, 2.2500e+01, 8.4000e+01, 2.5600e+00,
         2.2900e+00, 4.3000e-01, 1.0400e+00, 2.9000e+00, 9.3000e-01, 3.1900e+00,
         3.8500e+02],
        [1.3580e+01, 1.6600e+00, 2.3600e+00, 1.9100e+01, 1.0600e+02, 2.8600e+00,
         3.1900e+00, 2.2000e-01, 1.9500e+00, 6.9000e+00, 1.0900e+00, 2.8800e+00,
         1.5150e+03],
        [1.1610e+01, 1.3500e+00, 2.7000e+00, 2.0000e+01, 9.4000e+01, 2.7400e+00,
         2.9200e+00, 2.9000e-01, 2.4900e+00, 2.6500e+00, 9.6000e-01, 3.2600e+00,
         6.8000e+02]]) 
 tensor([[2.],
        [2.],
        [1.],
        [2.]])


In [28]:
# trainig loop 

num_epochs = 2
total_samples = len(dataset)
batch_size = 4
n_iterations = math.ceil(total_samples/batch_size)

for epoch in range(num_epochs):
  for i,(inputs,labels) in enumerate(dataloader):
    #forward,backward,update

    if (i+1) % 5 == 0 :
      print(f'epoch {epoch+1}/{num_epochs},step {i+1}/{n_iterations}, input {inputs.shape} ')   # each batch has 4 samples with 13 features

epoch 1/2,step 5/45, input torch.Size([4, 13]) 
epoch 1/2,step 10/45, input torch.Size([4, 13]) 
epoch 1/2,step 15/45, input torch.Size([4, 13]) 
epoch 1/2,step 20/45, input torch.Size([4, 13]) 
epoch 1/2,step 25/45, input torch.Size([4, 13]) 
epoch 1/2,step 30/45, input torch.Size([4, 13]) 
epoch 1/2,step 35/45, input torch.Size([4, 13]) 
epoch 1/2,step 40/45, input torch.Size([4, 13]) 
epoch 1/2,step 45/45, input torch.Size([2, 13]) 
epoch 2/2,step 5/45, input torch.Size([4, 13]) 
epoch 2/2,step 10/45, input torch.Size([4, 13]) 
epoch 2/2,step 15/45, input torch.Size([4, 13]) 
epoch 2/2,step 20/45, input torch.Size([4, 13]) 
epoch 2/2,step 25/45, input torch.Size([4, 13]) 
epoch 2/2,step 30/45, input torch.Size([4, 13]) 
epoch 2/2,step 35/45, input torch.Size([4, 13]) 
epoch 2/2,step 40/45, input torch.Size([4, 13]) 
epoch 2/2,step 45/45, input torch.Size([2, 13]) 
